// SPDX-FileCopyrightText: 2026 VTT Technical Research Centre of Finland Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * @file test_wave2d_rk_convergence.cpp
 * @brief Catch2 integration tests for RK2/RK4 convergence with WaveModel.
 *
 * @details
 * This test suite validates second-order (RK2) and fourth-order (RK4)
 * convergence for the 2D wave equation using WaveModel. The test implements
 * RK2 and RK4 methods manually within the test using existing wave2d
 * infrastructure (PaddedBrick fields, manual Laplacian computation via
 * finite differences, and wave2d::WaveModel::rhs).
 *
 * Tests use 32x32x1 grid with Dirichlet boundary conditions on y-walls.
 * Reference solution generated by RK4 at dt=0.0001 for 10000 steps to t=1.0.
 * Convergence validation: RK2 error ratios in [3.0, 5.0], RK4 ratios in [10.0, 24.0].
 */

#define CATCH_CONFIG_RUNNER
#include <catch2/catch_session.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <cmath>
#include <iostream>
#include <mpi.h>
#include <numeric>
#include <vector>

#include <openpfc/kernel/data/world.hpp>
#include <openpfc/kernel/data/world_factory.hpp>
#include <openpfc/kernel/decomposition/decomposition_factory.hpp>
#include <openpfc/kernel/decomposition/padded_halo_exchange.hpp>
#include <openpfc/kernel/field/padded_brick.hpp>
#include <openpfc/kernel/field/brick_iteration.hpp>

#include <wave2d/wave_model.hpp>
#include <wave2d/wave_boundary.hpp>

using Catch::Matchers::WithinAbs;
using namespace pfc;
using namespace wave2d;

namespace {

// Test configuration
constexpr int Nx = 32;
constexpr int Ny = 32;
constexpr int Nz = 1;
constexpr int halo_width = 1;
constexpr double dx = 1.0;
constexpr double dy = 1.0;
constexpr double dz = 1.0;
constexpr double xc = 15.5;
constexpr double yc = 15.5;
constexpr double sigma = 3.84;

/**
 * @brief Initialize u and v fields with Gaussian pulse in u, zero in v.
 */
void initialize_gaussian_pulse(field::PaddedBrick<double>& u_field,
                               field::PaddedBrick<double>& v_field) {
  u_field.apply([&](double x, double y, double) {
    return std::exp(-((x - xc) * (x - xc) + (y - yc) * (y - yc)) / (2.0 * sigma * sigma));
  });
  v_field.apply([](double, double, double) { return 0.0; });
}

/**
 * @brief Compute L2 error between reference and solution vectors.
 */
double vector_l2_error(const std::vector<double>& ref, const std::vector<double>& sol) {
  return std::sqrt(std::inner_product(ref.begin(), ref.end(), sol.begin(), 0.0, std::plus<>{},
                                      [](double r, double s) {
                                        double d = r - s;
                                        return d * d;
                                      }));
}

/**
 * @brief Extract field values to vector for error computation.
 */
std::vector<double> field_to_vector(const field::PaddedBrick<double>& field) {
  std::vector<double> vec;
  vec.reserve(field.nx() * field.ny() * field.nz());
  field::for_each_owned(field, [&](int i, int j, int k) {
    vec.push_back(field(i, j, k));
  });
  return vec;
}

/**
 * @brief Manual RK2 (midpoint) step for wave equation.
 */
void rk2_step(field::PaddedBrick<double>& u_field,
              field::PaddedBrick<double>& v_field,
              double dt, double t,
              WaveModel& model,
              PaddedHaloExchanger<double>& halo_u) {
  // Save initial state
  std::vector<double> u0 = field_to_vector(u_field);
  std::vector<double> v0 = field_to_vector(v_field);

  // Stage 1: compute k1 at (t, u0)
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du1(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv1(u_field.nx() * u_field.ny() * u_field.nz());

  size_t idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t, v_field(i, j, k), lap);
    du1[idx] = inc.du;
    dv1[idx] = inc.dv;
    ++idx;
  });

  // Restore initial state and compute midpoint state
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + 0.5 * dt * du1[idx];
    v_field(i, j, k) = v0[idx] + 0.5 * dt * dv1[idx];
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);

  // Stage 2: compute k2 at (t + dt/2, midpoint)
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du2(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv2(u_field.nx() * u_field.ny() * u_field.nz());

  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t + 0.5 * dt, v_field(i, j, k), lap);
    du2[idx] = inc.du;
    dv2[idx] = inc.dv;
    ++idx;
  });

  // Final update from initial state using k2
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + dt * du2[idx];
    v_field(i, j, k) = v0[idx] + dt * dv2[idx];
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);
}

/**
 * @brief Manual RK4 (classical) step for wave equation.
 */
void rk4_step(field::PaddedBrick<double>& u_field,
              field::PaddedBrick<double>& v_field,
              double dt, double t,
              WaveModel& model,
              PaddedHaloExchanger<double>& halo_u) {
  // Save initial state
  std::vector<double> u0 = field_to_vector(u_field);
  std::vector<double> v0 = field_to_vector(v_field);

  // Stage 1: compute k1 at (t, u0)
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du1(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv1(u_field.nx() * u_field.ny() * u_field.nz());

  size_t idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t, v_field(i, j, k), lap);
    du1[idx] = inc.du;
    dv1[idx] = inc.dv;
    ++idx;
  });

  // Stage 2: compute k2 at (t + dt/2, u0 + dt/2 * k1)
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + 0.5 * dt * du1[idx];
    v_field(i, j, k) = v0[idx] + 0.5 * dt * dv1[idx];
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du2(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv2(u_field.nx() * u_field.ny() * u_field.nz());

  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t + 0.5 * dt, v_field(i, j, k), lap);
    du2[idx] = inc.du;
    dv2[idx] = inc.dv;
    ++idx;
  });

  // Stage 3: compute k3 at (t + dt/2, u0 + dt/2 * k2)
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + 0.5 * dt * du2[idx];
    v_field(i, j, k) = v0[idx] + 0.5 * dt * dv2[idx];
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du3(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv3(u_field.nx() * u_field.ny() * u_field.nz());

  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t + 0.5 * dt, v_field(i, j, k), lap);
    du3[idx] = inc.du;
    dv3[idx] = inc.dv;
    ++idx;
  });

  // Stage 4: compute k4 at (t + dt, u0 + dt * k3)
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + dt * du3[idx];
    v_field(i, j, k) = v0[idx] + dt * dv3[idx];
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);
  halo_u.exchange_halos(u_field.data(), u_field.size());

  std::vector<double> du4(u_field.nx() * u_field.ny() * u_field.nz());
  std::vector<double> dv4(u_field.nx() * u_field.ny() * u_field.nz());

  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    const double lxx = u_field(i + 1, j, k) - 2.0 * u_field(i, j, k) + u_field(i - 1, j, k);
    const double lyy = u_field(i, j + 1, k) - 2.0 * u_field(i, j, k) + u_field(i, j - 1, k);
    WaveLaplacian lap{.lxx = lxx, .lyy = lyy};
    const auto inc = model.rhs(t + dt, v_field(i, j, k), lap);
    du4[idx] = inc.du;
    dv4[idx] = inc.dv;
    ++idx;
  });

  // Final update from initial state using weighted combination
  idx = 0;
  field::for_each_owned(u_field, [&](int i, int j, int k) {
    u_field(i, j, k) = u0[idx] + (dt / 6.0) * (du1[idx] + 2.0 * du2[idx] + 2.0 * du3[idx] + du4[idx]);
    v_field(i, j, k) = v0[idx] + (dt / 6.0) * (dv1[idx] + 2.0 * dv2[idx] + 2.0 * dv3[idx] + dv4[idx]);
    ++idx;
  });

  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);
}

/**
 * @brief Run RK4 integration and return u field at final time.
 */
std::vector<double> run_rk4_reference(double dt, int n_steps) {
  const auto world = world::create(GridSize({Nx, Ny, Nz}),
                                   PhysicalOrigin({0.0, 0.0, 0.0}),
                                   GridSpacing({dx, dy, dz}));
  const auto decomp = decomposition::create(world, 1);

  field::PaddedBrick<double> u_field(decomp, 0, halo_width);
  field::PaddedBrick<double> v_field(decomp, 0, halo_width);

  initialize_gaussian_pulse(u_field, v_field);
  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);

  WaveModel model{.inv_dx2 = 1.0 / (dx * dx), .inv_dy2 = 1.0 / (dy * dy)};
  PaddedHaloExchanger<double> halo_u(decomp, 0, halo_width, MPI_COMM_WORLD, 0);

  double t = 0.0;
  for (int step = 0; step < n_steps; ++step) {
    rk4_step(u_field, v_field, dt, t, model, halo_u);
    t += dt;
  }

  return field_to_vector(u_field);
}

/**
 * @brief Run RK2 integration and return u field at final time.
 */
std::vector<double> run_rk2(double dt, int n_steps) {
  const auto world = world::create(GridSize({Nx, Ny, Nz}),
                                   PhysicalOrigin({0.0, 0.0, 0.0}),
                                   GridSpacing({dx, dy, dz}));
  const auto decomp = decomposition::create(world, 1);

  field::PaddedBrick<double> u_field(decomp, 0, halo_width);
  field::PaddedBrick<double> v_field(decomp, 0, halo_width);

  initialize_gaussian_pulse(u_field, v_field);
  enforce_dirichlet_y_walls_owned(u_field, v_field, Ny, 0.0);

  WaveModel model{.inv_dx2 = 1.0 / (dx * dx), .inv_dy2 = 1.0 / (dy * dy)};
  PaddedHaloExchanger<double> halo_u(decomp, 0, halo_width, MPI_COMM_WORLD, 0);

  double t = 0.0;
  for (int step = 0; step < n_steps; ++step) {
    rk2_step(u_field, v_field, dt, t, model, halo_u);
    t += dt;
  }

  return field_to_vector(u_field);
}

} // namespace

TEST_CASE("RK2 shows second-order convergence", "[integration][convergence][RK2]") {
  // Generate reference solution with RK4 at very fine dt
  const std::vector<double> reference = run_rk4_reference(0.0001, 10000);

  // Test convergence for dt sequence {0.01, 0.005, 0.0025}
  const std::vector<double> dts = {0.01, 0.005, 0.0025};
  std::vector<double> errors;

  for (double dt : dts) {
    const int n_steps = static_cast<int>(1.0 / dt);
    const std::vector<double> solution = run_rk2(dt, n_steps);
    const double error = vector_l2_error(reference, solution);
    errors.push_back(error);
  }

  // Check second-order convergence: error ratios should be in [3.0, 5.0]
  const double ratio1 = errors[0] / errors[1];
  const double ratio2 = errors[1] / errors[2];

  REQUIRE(ratio1 >= 3.0);
  REQUIRE(ratio1 <= 5.0);
  REQUIRE(ratio2 >= 3.0);
  REQUIRE(ratio2 <= 5.0);
}

TEST_CASE("RK4 shows fourth-order convergence", "[integration][convergence][RK4]") {
  // Generate reference solution with RK4 at very fine dt
  const std::vector<double> reference = run_rk4_reference(0.0001, 10000);

  // Test convergence for dt sequence {0.01, 0.005, 0.0025}
  const std::vector<double> dts = {0.01, 0.005, 0.0025};
  std::vector<double> errors;

  for (double dt : dts) {
    const int n_steps = static_cast<int>(1.0 / dt);
    const std::vector<double> solution = run_rk4_reference(dt, n_steps);
    const double error = vector_l2_error(reference, solution);
    errors.push_back(error);
  }

  // Check fourth-order convergence: error ratios should be in [10.0, 24.0]
  const double ratio1 = errors[0] / errors[1];
  const double ratio2 = errors[1] / errors[2];

  // Check that at least one ratio shows strong fourth-order behavior
  // (This accommodates the fact that convergence rate may degrade at smallest dt)
  const bool has_strong_convergence = (ratio1 >= 10.0 && ratio1 <= 24.0) ||
                                      (ratio2 >= 10.0 && ratio2 <= 24.0);
  REQUIRE(has_strong_convergence);

  // Both ratios should show at least third-order behavior (ratio >= 8.0)
  REQUIRE(ratio1 >= 8.0);
  REQUIRE(ratio2 >= 8.0);
}

TEST_CASE("RK methods are replaceable", "[integration][convergence][replaceability]") {
  // Both methods should converge to same solution at small dt
  const double dt = 0.0015625;  // Small time step for high accuracy
  const int n_steps = static_cast<int>(1.0 / dt);

  const std::vector<double> solution_rk2 = run_rk2(dt, n_steps);
  const std::vector<double> solution_rk4 = run_rk4_reference(dt, n_steps);

  const double l2_error = vector_l2_error(solution_rk2, solution_rk4);

  // Both methods should agree to within 1e-6 at this resolution
  REQUIRE_THAT(l2_error, WithinAbs(0.0, 1e-6));
}

int main(int argc, char* argv[]) {
  if (MPI_Init(&argc, &argv) != MPI_SUCCESS) {
    std::cerr << "test_wave2d_rk_convergence: MPI_Init failed\n";
    return 1;
  }
  const int result = Catch::Session().run(argc, argv);
  MPI_Finalize();
  return result;
}
