# SPDX-FileCopyrightText: 2025 VTT Technical Research Centre of Finland Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM openpfc-builder as tester

# Test project
RUN (cd build/Debug/tests && ctest)
