name: OpenPFC CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: docker build -t openpfc-builder -f containers/cicd/Dockerfile.build .

    - name: Run unit tests
      run: docker build -t openpfc-tester -f containers/cicd/Dockerfile.test .

  generate_docs:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
    - name: Generate documentation
      run: docker build -t openpfc-docs -f containers/cicd/Dockerfile.docs .
